-- ============================================================
--  claw-me.com — Channel Pairing Migration
--  Run in: Supabase Dashboard → SQL Editor → New Query
-- ============================================================

-- ── PAIRING TOKENS ──────────────────────────────────────────
-- One-time tokens generated by the admin dashboard.
-- Tenant clicks "Connect Telegram" → row inserted → deep link shown.
-- n8n workflow redeems the token on /start → marks used_at.
CREATE TABLE IF NOT EXISTS pairing_tokens (
  token          TEXT PRIMARY KEY DEFAULT replace(gen_random_uuid()::text, '-', ''),
  tenant_id      UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  channel        TEXT NOT NULL CHECK (channel IN ('telegram','whatsapp','sms','slack')),
  expires_at     TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '24 hours',
  used_at        TIMESTAMPTZ,                          -- null = unused
  created_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS pairing_tokens_tenant_idx ON pairing_tokens(tenant_id);
CREATE INDEX IF NOT EXISTS pairing_tokens_channel_idx ON pairing_tokens(channel, token);

-- ── CHANNEL PAIRINGS ────────────────────────────────────────
-- Active connections between tenants and messaging channel users.
-- One tenant may have multiple pairings (e.g. Telegram + WhatsApp).
-- One channel_user_id can only be paired to one tenant per channel.
CREATE TABLE IF NOT EXISTS channel_pairings (
  id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id        UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  channel          TEXT NOT NULL CHECK (channel IN ('telegram','whatsapp','sms','slack')),
  channel_user_id  TEXT NOT NULL,   -- Telegram chat_id | E.164 phone | Slack user_id
  channel_username TEXT,            -- human-readable display name in that channel
  active           BOOLEAN NOT NULL DEFAULT true,
  metadata         JSONB DEFAULT '{}',
  paired_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at       TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (channel, channel_user_id)  -- one user per channel, one tenant
);

CREATE INDEX IF NOT EXISTS channel_pairings_tenant_idx
  ON channel_pairings(tenant_id, channel, active);
CREATE INDEX IF NOT EXISTS channel_pairings_lookup_idx
  ON channel_pairings(channel, channel_user_id, active);

CREATE TRIGGER channel_pairings_updated_at
  BEFORE UPDATE ON channel_pairings
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ── RLS ─────────────────────────────────────────────────────
ALTER TABLE pairing_tokens    ENABLE ROW LEVEL SECURITY;
ALTER TABLE channel_pairings  ENABLE ROW LEVEL SECURITY;

-- Tenants can see their own tokens and pairings
CREATE POLICY pairing_tokens_tenant ON pairing_tokens
  FOR ALL USING (tenant_id = current_tenant_id());

CREATE POLICY channel_pairings_tenant ON channel_pairings
  FOR ALL USING (tenant_id = current_tenant_id());

-- n8n (service role key) bypasses RLS — no policy needed for service key
